//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebtTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Debt()
        {
            this.PaidDebts = new HashSet<PaidDebts>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public double Ammount { get; set; }
        public System.DateTime Date { get; set; }
        public int TypeId { get; set; }
        public bool DoesRepeat { get; set; }
        public int RepeatCount { get; set; }
        public string UserOwner { get; set; }
        public string ForUser { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual DebtType DebtType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaidDebts> PaidDebts { get; set; }
    }
}
